-- V39: Seed secretarias_municipais with Sinop-MT data
INSERT INTO secretarias_municipais (codigo, nome, ativo) VALUES
('02', 'GABINETE DO CHEFE DO EXECUTIVO', TRUE),
('03', 'SECRETARIA MUNICIPAL DE ADMINISTRAÇÃO E MODERNIZAÇÃO', TRUE),
('04', 'SECRETARIA MUNICIPAL DE FINANÇAS E ORÇAMENTO', TRUE),
('07', 'SECRETARIA MUNICIPAL DE OBRAS E SERVIÇOS URBANOS', TRUE),
('08', 'SECRETARIA MUNICIPAL DE SEGURANÇA E TRÂNSITO', TRUE),
('10', 'SECRETARIA MUNICIPAL DE MEIO AMBIENTE E DESENVOLVIMENTO SUSTENTÁVEL', TRUE),
('11', 'SECRETARIA MUNICIPAL DE EDUCAÇÃO', TRUE),
('12', 'SECRETARIA MUNICIPAL DE ASSISTÊNCIA SOCIAL', TRUE),
('13', 'SECRETARIA MUNICIPAL DE DESENVOLVIMENTO ECONÔMICO', TRUE),
('14', 'SECRETARIA MUNICIPAL DE SAÚDE', TRUE),
('17', 'SECRETARIA DE GOVERNO E PLANEJAMENTO ESTRATÉGICO', TRUE),
('20', 'SECRETARIA MUNICIPAL DE CULTURA, ESPORTE E TURISMO', TRUE),
('21', 'SECRETARIA MUNICIPAL DE PLANEJAMENTO URBANO E HABITAÇÃO', TRUE),
('22', 'PROCURADORIA GERAL DO MUNICÍPIO', TRUE)
ON CONFLICT (codigo) DO UPDATE SET nome = EXCLUDED.nome;